version: '2.1'

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy infrastructure stack
          command: |
            aws cloudformation deploy \
            --stack-name myInfrastructure \
            --template-body file://template.yml --region us-east-1
workflows:
  create-resources:
    jobs:
      - create_infrastructure