version: 2.1

workflows:
  my-workflow:
    jobs:
      - print_pipeline_job

jobs:
  print_pipeline_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1 
      - run: 
          command: echo Your command failed
          when: on_fail


