version: '2.1'

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: export AWS_PROFILE=default
      - run: aws s3 ls
      
workflows:
  create-resources:
    jobs:
      - create_infrastructure