version: 2.1

workflows:
  test-env-vars:
    jobs:
      - save_hello_world_output

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          command: |
            echo "text to output here" > output.txt
      - persist_to_workspace:
          paths:
            - output.txt
       
  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: output.txt
      - run:
          command: |
            cat output.txt
