version: '2.1'

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: export AWS_PROFILE=default
      - run: aws cloudformation create-stack --stack-name myInfrastructure --template-body file://template.yml --region=us-west-2

workflows:
  create-resources:
    jobs:
      - create_infrastructure