version: '2.1'
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create and deploy Front End
          command: |
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-override NAME="${CIRCLE_WORKFLOW_ID:0:7}"
workflows:
  create-resources:
    jobs:
      - create_and_deploy_front_end
